# Generated by Django 4.1.1 on 2022-10-18 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(8)], verbose_name='Цена'),
        ),
    ]
