# Generated by Django 4.1.1 on 2022-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=8, verbose_name='Цена'),
        ),
    ]
