# Generated by Django 4.1.1 on 2022-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
