# Generated by Django 4.1.1 on 2022-12-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_help_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Фото'},
        ),
    ]
