# Generated by Django 4.1.1 on 2022-10-18 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон'),
        ),
    ]
