# Generated by Django 4.1.1 on 2022-10-18 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_phone_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Описание продавца'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Телефон должнен быть похож на: '+999999999'. ", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
