# Generated by Django 4.1.1 on 2022-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_bio_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Europe', (('FR', 'France'), ('ES', 'Spain'))), ('Africa', (('MA', 'Morocco'), ('DZ', 'Algeria')))], max_length=300),
        ),
    ]
