# Generated by Django 4.1.1 on 2022-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Приморский край', (('Владивосток', 'Владивосток'), ('Находка', 'Находка'))), ('Сахалин', (('Южно Сахалинск', 'Южно Сахалинск'), ('Холмск', 'Холмск')))], max_length=300),
        ),
    ]
